---
- name: "Include tasks for {{ ansible_os_family }} - {{ ansible_distribution }}"
  include_tasks: "{{ ansible_distribution }}/main.yml"

- name: "Install duply and duplicity packages"
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ backup_duply_packages }}"
